version: "3.3"
services:
  postgres:
    container_name: db_spotify
    image: postgres:14.2
    volumes:
      - spotify-api-postgres-data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    healthcheck:
      test:
        ["CMD-SHELL", "pg_isready -h ${DB_HOST} -d ${DB_DATABASE} -p ${DB_PORT} -U ${DB_USERNAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      options:
        max-size: 10k
  redis:
    container_name: redis_spotify-api
    image: redis:6.2
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - spotify-api-redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    logging:
      options:
        max-size: 10k
  maildev:
    image: maildev/maildev
    ports:
      - "1080:80"
      - "1025:25"

volumes:
  spotify-api-postgres-data:
    external: true
  spotify-api-redis-data:
