NODE_ENV=development
PORT=3000
HOST=http://localhost:3000

NODE_ENV=development
PORT=3000

API_URL=localhost:3000

DB_PORT=__DB_PORT__
DB_HOST=__DB_HOST__
DB_DATABASE=__DB_DATABASE__
DB_USERNAME=__DB_USERNAME__
DB_PASSWORD=__DB_PASSWORD__

AUTH_TOKEN_SECRET=secret

REDIS_HOST=__DB_HOST__
REDIS_PORT=__REDIS_PORT__

CLIENT_URL=http://localhost:4200
